### ISSUE TITLE
Raspberry Debug Settings: Can't find startup project in solution folder

### ISSUE THREAD

**Issue by LwServices** [nforgeio/RaspberryDebugger#17]
After installation, ssh setup works fine. Ssh key were generated.
Then I Try to open "Raspberry Debug Settings" Dialog. nothing happens.
No error log entry  when I use devenv /log "%USERPROFILE%\MyVSLog.xml"
also no error popup

what to do?

Thank you.

Update: I have try to debug this extesion and I get an null project
![image](https://user-images.githubusercontent.com/667742/102768540-a26fa500-4381-11eb-8c6a-2db533db968d.png)

**Comment by LwServices** [comment]
![image](https://user-images.githubusercontent.com/667742/102770883-25dec580-4385-11eb-982b-e22cae4512d5.png)
![image](https://user-images.githubusercontent.com/667742/102770963-4b6bcf00-4385-11eb-8d41-98cdbe66f34e.png)

I have fixed my issue and moved the startup project to root solution folder

**Comment by jefflill** [comment]
@LwServices mentioned that the startup project could not be found when it resides in a **solution folder**.

**Comment by jefflill** [comment]
*FIXED:** I was looking for the wrong project kind.

**Comment by jefflill** [comment]
@LwServices: FYI: I just published these changes as v0.6 to the Visual Studio Marketplace.
