### ISSUE TITLE
Add Target Group to Raspberry Debug Settings...

### ISSUE THREAD

**Issue by jefflill** [nforgeio/RaspberryDebugger#20]
@LwServices: I saw the note you left about _showing the GPIO group in the configuration_.

Are you thinking there should be a check box in the Raspberry Debug Settings dialog enabling/disabling this?  I wonder if that's really necessary if we just enable this by default.  I guess this might be useful for people whose Raspberry user account isn't a member.

This would be easy to add and the settings dialog could use a bit more meat, so I'll add this and have it default to checked.

**Comment by LwServices** [comment]
@jefflill In my opinion we need somewhere a property labeled GroupName or similar. gpio group is very specific and will not work for most of the use case.
We have the choice: 
Application based: What about lanch.json or another config.json file? 
Connection based: Add somewhere to ~/.raspberry

**Comment by jefflill** [comment]
I'm thinking about adding this to the **Project/Raspberry Debug Settings** dialog which persists its settings as `.vs\raspberry-projects.json` in the solution.

I could add a group textbox there and default it to **"gpio**.  **Does that make sense?**

I've been assuming that most people wouldn't worry too much about creating custom groups on their Raspberry but I suppose the developers using Visual Studio and .NET will tend to be more advance than people hacking away with lesser tools :)

**Comment by LwServices** [comment]
Before I found your solution I played with https://github.com/unosquare/sshdeploy 
This guys use csproj file to store theirs settings. You could get the parser from there 
https://github.com/unosquare/sshdeploy/tree/master/Unosquare.Labs.SshDeploy/Utils

otherwise this solution what you just mentioned works als for me fine.

**Comment by jefflill** [comment]
Cool, I think I see what's happening: I've been debugging so far using the default **pi** user which is already a member of the **gpio** group, so GPIO access would have worked for me if I had actually tested it.

You must be doing something more advanced by using other user accounts and perhaps your own groups which will be the case for serious projects.  I've gone ahead and added this to the debug settings:

![image](https://user-images.githubusercontent.com/4908431/102816377-c5e71f80-4382-11eb-836f-c71a7b6e1c37.png)

I'll have a look at #17 and then do a release later this afternoon.
