### ISSUE TITLE
Fails on [dotnet publish]

### ISSUE THREAD

**Issue by skima74** [nforgeio/RaspberryDebugger#31]
I've installed v1.4 to give it a try.

It seems to connect to target just fine:
![image](https://user-images.githubusercontent.com/45507962/112831227-3ad69d80-90c6-11eb-85c2-9db3a6e82de8.png)

But when I try to run the app, I get :
![image](https://user-images.githubusercontent.com/45507962/112831245-41fdab80-90c6-11eb-9f05-221876af9e7a.png)

The output window doesnt give many clues:
![image](https://user-images.githubusercontent.com/45507962/112831344-622d6a80-90c6-11eb-9c53-7076118ec9f7.png)

I'm using VS 16.9.2

Bests,
skima

**Comment by jefflill** [comment]
I've seen another report of this happening (#28) been able to repo the problem myself.  I proactively tried something that might have fixed this but apparently it's not working.

Do you mind if I ask you a few questions?

**Is this a console or web project?**

**Does your solution include more than on project?**

**Does your solution include any solution folders?**

I am currently logging all of the output from the `dotnet publish` command when it returns a non-zero exit code and we don't appear to be seeing an error here.  I've added additional code to log any exceptions thrown.  Perhaps the extension is unable to launch **dotnet** in your environment.

Can you please try **upgrading to v1.5** and **letting me know if that works?**

**Comment by skima74** [comment]
Hi Jeff,
Thanks for the prompt reply. 
a) Its ASP.NET gRPC project
b) There are several projects in the solution, but this is the only project targeting the Raspberry Pi.
c) The solution has .git and .vs hidden folders
d) I tried version 1.5. The error count has increased from 4 to 5. Only the error count is reported, not the actual errors, as below.
[raspberry]: INFO: Checking for native Windows OpenSSH client
[raspberry]: INFO: Building: C:\Users\...\LineController_GrpcService.csproj
[raspberry]: ERROR: Build failed: [5] errors

Let me know if there is anything else I can do.
Bests,
skima

**Comment by jefflill** [comment]
So I think you have compiler errors in your project:
```
[raspberry]: ERROR: Build failed: [5] errors
```
I've just published v1.6 that actually logs the specific errors and tells the user to look at the Build/Output window for more details.

I'm going to go ahead and close this but feel free to reopen it if you have more issues.  Thanks for you input,
