### ISSUE TITLE
Remote Debug fails for projects that multi target several frameworks (Error NETSDK1129)

### ISSUE THREAD

**Issue by MagicAndre1981** [nforgeio/RaspberryDebugger#36]
The remote debug fails for projects that multi target several frameworks added in the csproj:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>netcoreapp3.1;net5.0</TargetFrameworks>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
  </PropertyGroup>

</Project>
```

Trying to debug generates an error message

![raspberrydebugger](https://user-images.githubusercontent.com/8274816/122180186-7ba1af80-ce88-11eb-830e-681aa529c88c.png)

```
[raspberry]: INFO: Checking for native Windows OpenSSH client
[raspberry]: INFO: Building: D:\FooApp\FooApp\FooApp.csproj
[raspberry]: INFO: Build succeeded
[raspberry]: INFO: Publishing: D:\FooApp\FooApp\FooApp.csproj
[raspberry]: ERROR: Publish failed: ExitCode=1
Microsoft (R)-Build-Engine, Version 16.10.1+2fd48ab73 für .NET
Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.
  Wiederherzustellende Projekte werden ermittelt...
  "D:\FooApp\FooApp\FooApp.csproj" wiederhergestellt (in 89 ms).
C:\Program Files\dotnet\sdk\5.0.301\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.CrossTargeting.targets(27,5): error NETSDK1129: Das Ziel für "Publish" wird ohne Angabe eines Zielframeworks nicht unterstützt. Das aktuelle Projekt verwendet mehrere Frameworks als Ziel. Sie müssen das Framework für die veröffentlichte Anwendung angeben. [D:\FooApp\FooApp\FooApp.csproj]
```

when I only use 1 targetframework, debug works

**Comment by MagicAndre1981** [comment]
any update? When I try to debug the extension from source code I only get a ghosted VS2019 window and VS is not responding

**Comment by MagicAndre1981** [comment]
ok, on a second VM debugging works and I can see in [PublishProjectAsync](https://github.com/nforgeio/RaspberryDebugger/blob/c1b902e2b1320b32eb3a52f4fba1c8631eba7776/RaspberryDebugger/DebugHelper.cs#L384) the [--framework option is not set](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-publish#options). 

So I added a property Framework to `ProjectProperties` and set it in `CopyFrom` to value of `FriendlyTargetFramework`, but this is always the first value from TargetFrameworks and not the value from the debug settings of the project.

**Comment by MagicAndre1981** [comment]
ok, I fixed it in my local copy. I need to use `IActiveDebugFrameworkServices` to get information about debugging info (configuration, platform and targetframework).

![vs_settings_debug_6](https://user-images.githubusercontent.com/8274816/125252001-2fffeb80-e2f8-11eb-8734-a0c3bff9b511.png)

![vs_settings_debug_7](https://user-images.githubusercontent.com/8274816/125252045-3b531700-e2f8-11eb-8acc-20be704b46a7.png)


And when I pass this retrieved targetframework to dotnet publish command in DebugHelper, the publish and debug works. 

![.net core 3.1](https://user-images.githubusercontent.com/8274816/125247911-bd8d0c80-e2f3-11eb-9e39-6b6a6e0f060c.png)

![.net 5.0](https://user-images.githubusercontent.com/8274816/125250632-c6331200-e2f6-11eb-9138-1539f7c970c8.png)


But there is an issue. The stable nuget package [Microsoft.VisualStudio.ProjectSystem.Managed 2.0.6142705 on nuget.org](https://www.nuget.org/packages/Microsoft.VisualStudio.ProjectSystem.Managed/) misses the required Interface  `IActiveDebugFrameworkServices` and I to use the [pre-release feed on azure ](https://pkgs.dev.azure.com/azure-public/vside/_packaging/vs-impl/nuget/v3/index.json) to get the 16.10 version.

Now there is the question what to do? Is it ok to use a lot of pre-release packages?

**Comment by MagicAndre1981** [comment]
any update @jefflill ? Should I create a PR by using a lot of pre-Release nugets from Azure feed? I added a nuget.config wit the feed so build will work.

**Comment by MagicAndre1981** [comment]
> Should I create a PR by using a lot of pre-Release nugets from Azure feed? I added a nuget.config wit the feed so build will work.

I created now the PR #38  with `nuget.config` that gets the required packages @jefflill

**Comment by MagicAndre1981** [comment]
@jefflill are you working again on the extension?

**Comment by jefflill** [comment]
Yeah, I’ve been thinking about releasing the VS 2022 support pull request,
but I’ve been busy with another project.

Want to help?

—Jeff

**Comment by MagicAndre1981** [comment]
where you able to get the 2022 versions of my added libs? The user who forked it and added VS2022 support reverted my PR because we was not able to get the prerelease libs from private nuget feeds. I haven't checked if those feeds are still valid.
