### ISSUE TITLE
Package did not load correctly - VS2019 v16.5

### ISSUE THREAD

**Issue by Vegz78** [nforgeio/RaspberryDebugger#37]
Hi,

Just tried to install your RaspberryDebugger extension, but it fails to load with an error similar to this:
https://i.stack.imgur.com/osqFR.png
I also tried most of the [suggestions in the same forum](https://stackoverflow.com/questions/17574089/how-can-i-fix-the-microsoft-visual-studio-error-package-did-not-load-correctly) without any luck.

From the ActivityLog.xlm:
```xml
<entry>
    <record>1815</record>
    <time>2021/06/27 12:57:17.025</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>SetSite failed for package [RaspberryDebuggerPackage]Source: &apos;RaspberryDebugger&apos; Description: Could not load file or assembly &apos;Microsoft.VisualStudio.Threading, Version=16.7.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos; or one of its dependencies. Systemet finner ikke angitt fil.&#x000D;&#x000A;System.IO.FileNotFoundException: Could not load file or assembly &apos;Microsoft.VisualStudio.Threading, Version=16.7.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos; or one of its dependencies. Systemet finner ikke angitt fil.&#x000D;&#x000A;File name: &apos;Microsoft.VisualStudio.Threading, Version=16.7.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos;&#x000D;&#x000A;   at RaspberryDebugger.RaspberryDebuggerPackage.InitializeAsync(CancellationToken cancellationToken, IProgress`1 progress)&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.AsyncPackage.&lt;&gt;c__DisplayClass20_0.&lt;&lt;Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize&gt;b__1&gt;d.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.VisualStudio.Threading.JoinableTask.&lt;JoinAsync&gt;d__68.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e)&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.GetResult()&#x000D;&#x000A;&#x000D;&#x000A;WRN: Assembly binding logging is turned OFF.&#x000D;&#x000A;To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.&#x000D;&#x000A;Note: There is some performance penalty associated with assembly bind failure logging.&#x000D;&#x000A;To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].&#x000D;&#x000A;</description>
    <guid>{FED3A92C-C8E2-40A3-A38F-CE7D35088EA5}</guid>
    <hr>80070002</hr>
    <errorinfo></errorinfo>
  </entry>
  <entry>
    <record>1816</record>
    <time>2021/06/27 12:57:17.039</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>End package load [RaspberryDebuggerPackage]</description>
    <guid>{FED3A92C-C8E2-40A3-A38F-CE7D35088EA5}</guid>
    <hr>80070002</hr>
    <errorinfo></errorinfo>
  </entry>
</activity>
```

It mentions *missing* and _could not load file or assembly_ _"Microsoft.VisualStudio.Threading, Version=16.7.0.0"_.

I have many of those installed, but in my Visual Studio 2019 v16.5 installation folder, most notably:
- under ..\Common7\IDE\PublicAssemblies\ -> version 16.5.127...
- under ..\Common7\IDE\PrivateAssemblies\ -> version 15.8.192...

Do I have to upgrade VS2019 to use the RaspberryDebugger, could I install an older version, are there other dependencies I could install to make it work in VS2019 v16.5 or could you lower the required dependency version in the extension so that it is more backward compatible?

Or maybe you have any other suggestions on how I could get your extension to work in my VS2019 v16.5 installation?
(I sadly cannot upgrade VS2019 at the moment, due to older MacOS developer machine...). ;-)

**Comment by MagicAndre1981** [comment]
VS2019 16.5 is out of support for a while. 16.7/16.9 are longer supported, so update to one of those versions [via installer](https://stackoverflow.com/a/61359432/1466046)

**Comment by Vegz78** [comment]
Thanks for your reply and confirmation that I need to update VS2019 to make it work, @MagicAndre1981!

At the moment, upgrading above VS v16.5 sadly breaks other things for me. 

Is it correct to assume:
1. That VS v16.5 also will not be supported in any newer versions of Raspberry Debugger in the future?
2. That some of your older releases of Raspberry Debugger here on GitHub might still work with VS v16.5, and in that case which is the latest of your releases which will still work with VS v16.5?:
https://github.com/nforgeio/RaspberryDebugger/releases

**Comment by MagicAndre1981** [comment]
I'm only an user not the developer of the extension. 

Fork it and replace the 16.7 references with 16.5 or try to update the `devenv.exe.config` on your dev system to change [bindingRedirect ](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/redirect-assembly-versions#manually-edit-the-app-config-file)to use 16.5 but I'm not sure if this works.

**Comment by Vegz78** [comment]
Thanks again, @MagicAndre1981!

I'll look into this later, but this was very useful information and sounds reasonable enough as suggestions to close this issue, if the devs have their reasons for the particular ranges of backwards compatibility in each new release.

**Comment by MagicAndre1981** [comment]
> if the devs have their reasons for the particular ranges of backwards compatibility in each new release.

I guess at that time this was the most recent version. 

Best it to update VS to 16.10 and to 16.11 when it is released as this will be the final VS2019 update. This version will get updates for next years.
